// Lista de bancos brasileiros (código COMPE / ISPB).
// Fonte: BrasilAPI (https://brasilapi.com.br/api/banks/v1) — lista estática de fallback
// com os principais bancos; o BankSelect tenta atualizar via API em runtime.

export interface BankEntry {
  code: string; // código COMPE (3 dígitos, sem zeros à esquerda extras)
  name: string;
}

export const BRAZILIAN_BANKS: BankEntry[] = [
  { code: '1', name: 'Banco do Brasil' },
  { code: '3', name: 'Banco da Amazônia' },
  { code: '4', name: 'Banco do Nordeste' },
  { code: '7', name: 'BNDES' },
  { code: '10', name: 'Credicoamo' },
  { code: '12', name: 'Banco Inbursa' },
  { code: '14', name: 'Natixis Brasil' },
  { code: '17', name: 'BNY Mellon Banco' },
  { code: '21', name: 'Banestes' },
  { code: '24', name: 'Banco Bandepe' },
  { code: '25', name: 'Banco Alfa' },
  { code: '29', name: 'Banco Itaú Consignado' },
  { code: '33', name: 'Santander' },
  { code: '36', name: 'Banco Bradesco BBI' },
  { code: '37', name: 'Banco do Estado do Pará' },
  { code: '40', name: 'Banco Cargill' },
  { code: '41', name: 'Banrisul' },
  { code: '47', name: 'Banco do Estado de Sergipe (Banese)' },
  { code: '60', name: 'Confidence Câmbio' },
  { code: '63', name: 'Banco Ibi' },
  { code: '65', name: 'Banco AndBank' },
  { code: '69', name: 'Banco Crefisa' },
  { code: '70', name: 'BRB — Banco de Brasília' },
  { code: '74', name: 'Banco J. Safra' },
  { code: '75', name: 'Banco ABN Amro' },
  { code: '77', name: 'Banco Inter' },
  { code: '79', name: 'Banco Original do Agronegócio' },
  { code: '80', name: 'B&T Câmbio' },
  { code: '81', name: 'BancoSeguro' },
  { code: '82', name: 'Banco Topázio' },
  { code: '83', name: 'Banco da China Brasil' },
  { code: '84', name: 'Uniprime Norte do Paraná' },
  { code: '85', name: 'Cooperativa Central Ailos' },
  { code: '88', name: 'Banco Randon' },
  { code: '89', name: 'Credisan' },
  { code: '91', name: 'Unicred Central' },
  { code: '93', name: 'Pólocred' },
  { code: '94', name: 'Banco Finaxis' },
  { code: '95', name: 'Travelex Banco de Câmbio' },
  { code: '96', name: 'Banco B3' },
  { code: '97', name: 'Credisis' },
  { code: '100', name: 'Planner Corretora' },
  { code: '102', name: 'XP Investimentos' },
  { code: '104', name: 'Caixa Econômica Federal' },
  { code: '105', name: 'Lecca Crédito' },
  { code: '107', name: 'Banco Bocom BBM' },
  { code: '108', name: 'Portocred' },
  { code: '111', name: 'Oliveira Trust' },
  { code: '114', name: 'Central Cooperativa de Crédito no Estado do Espírito Santo' },
  { code: '117', name: 'Advanced Corretora' },
  { code: '119', name: 'Banco Western Union' },
  { code: '120', name: 'Banco Rodobens' },
  { code: '121', name: 'Banco Agibank' },
  { code: '122', name: 'Banco Bradesco BERJ' },
  { code: '124', name: 'Banco Woori Bank do Brasil' },
  { code: '125', name: 'Plural Banco' },
  { code: '126', name: 'BR Partners Banco de Investimento' },
  { code: '127', name: 'Codepe Corretora' },
  { code: '128', name: 'MS Bank' },
  { code: '129', name: 'UBS Brasil' },
  { code: '130', name: 'Caruana SCFI' },
  { code: '131', name: 'Tullett Prebon Brasil' },
  { code: '132', name: 'ICBC do Brasil' },
  { code: '133', name: 'Cresol Confederação' },
  { code: '134', name: 'BGC Liquidez' },
  { code: '136', name: 'Unicred' },
  { code: '138', name: 'Get Money Corretora' },
  { code: '139', name: 'Intesa Sanpaolo Brasil' },
  { code: '140', name: 'Nu Invest (Easynvest)' },
  { code: '142', name: 'Broker Brasil' },
  { code: '143', name: 'Treviso Corretora' },
  { code: '144', name: 'Bexs Banco de Câmbio' },
  { code: '145', name: 'Levycam Câmbio' },
  { code: '146', name: 'Guitta Corretora' },
  { code: '149', name: 'Facta Financeira' },
  { code: '157', name: 'ICAP do Brasil' },
  { code: '159', name: 'Casa do Crédito' },
  { code: '163', name: 'Commerzbank Brasil' },
  { code: '169', name: 'Banco Olé Bonsucesso Consignado' },
  { code: '173', name: 'BRL Trust Distribuidora' },
  { code: '174', name: 'Pernambucanas Financiadora' },
  { code: '177', name: 'Guide Investimentos' },
  { code: '180', name: 'CM Capital Markets' },
  { code: '183', name: 'Socred' },
  { code: '184', name: 'Banco Itaú BBA' },
  { code: '188', name: 'Ativa Investimentos' },
  { code: '190', name: 'Servicoop' },
  { code: '191', name: 'Nova Futura Corretora' },
  { code: '194', name: 'Parmetal Distribuidora' },
  { code: '196', name: 'Fair Corretora' },
  { code: '197', name: 'Stone Pagamentos' },
  { code: '208', name: 'Banco BTG Pactual' },
  { code: '212', name: 'Banco Original' },
  { code: '213', name: 'Banco Arbi' },
  { code: '217', name: 'Banco John Deere' },
  { code: '218', name: 'Banco BS2' },
  { code: '222', name: 'Banco Credit Agricole Brasil' },
  { code: '224', name: 'Banco Fibra' },
  { code: '233', name: 'Banco Cifra' },
  { code: '237', name: 'Bradesco' },
  { code: '241', name: 'Banco Clássico' },
  { code: '243', name: 'Banco Máxima' },
  { code: '246', name: 'Banco ABC Brasil' },
  { code: '249', name: 'Banco Investcred Unibanco' },
  { code: '250', name: 'BCV — Banco de Crédito e Varejo' },
  { code: '253', name: 'Bexs Corretora de Câmbio' },
  { code: '254', name: 'Paraná Banco' },
  { code: '259', name: 'Moneycorp Banco de Câmbio' },
  { code: '260', name: 'Nubank' },
  { code: '265', name: 'Banco Fator' },
  { code: '266', name: 'Banco Cédula' },
  { code: '268', name: 'Barigui Companhia Hipotecária' },
  { code: '269', name: 'Banco HSBC (HS Bank)' },
  { code: '270', name: 'Sagitur Corretora' },
  { code: '271', name: 'IB Corretora' },
  { code: '272', name: 'AGK Corretora de Câmbio' },
  { code: '273', name: 'Cooperativa de Crédito Rural de São Miguel do Oeste (Sulcredi)' },
  { code: '274', name: 'Money Plus SCMEPP' },
  { code: '276', name: 'Senff Crédito' },
  { code: '278', name: 'Genial Investimentos' },
  { code: '279', name: 'Cooperativa de Crédito Rural de Primavera do Leste' },
  { code: '280', name: 'Avista' },
  { code: '281', name: 'Cooperativa de Crédito Rural Coopavel' },
  { code: '283', name: 'RB Investimentos' },
  { code: '285', name: 'Frente Corretora' },
  { code: '286', name: 'Cooperativa de Crédito Rural de Ouro (Sulcredi)' },
  { code: '288', name: 'Carol Distribuidora' },
  { code: '290', name: 'PagSeguro (PagBank)' },
  { code: '292', name: 'BS2 Distribuidora' },
  { code: '293', name: 'Lastro RDV' },
  { code: '296', name: 'Visa (Banco Útil)' },
  { code: '298', name: "Vip's Corretora" },
  { code: '299', name: 'Banco Sorocred' },
  { code: '300', name: 'Banco de La Nación Argentina' },
  { code: '301', name: 'BPP Instituição de Pagamento' },
  { code: '306', name: 'Portopar Distribuidora' },
  { code: '307', name: 'Terra Investimentos' },
  { code: '309', name: 'Cambionet Corretora de Câmbio' },
  { code: '310', name: 'Vortx Distribuidora' },
  { code: '311', name: 'Dourada Corretora' },
  { code: '312', name: 'HSCM SCMEPP' },
  { code: '313', name: 'Amazônia Corretora' },
  { code: '315', name: 'Pi Distribuidora' },
  { code: '318', name: 'Banco BMG' },
  { code: '319', name: 'Ótimo Sociedade de Crédito' },
  { code: '320', name: 'China Construction Bank Brasil' },
  { code: '321', name: 'Crefaz SCMEPP' },
  { code: '322', name: 'Cooperativa de Crédito Rural de Abelardo Luz (Sulcredi)' },
  { code: '323', name: 'Mercado Pago' },
  { code: '324', name: 'Cartos Sociedade de Crédito Direto' },
  { code: '325', name: 'Órama Distribuidora' },
  { code: '326', name: 'Parati Crédito' },
  { code: '329', name: 'QI Sociedade de Crédito Direto' },
  { code: '330', name: 'Banco Bari' },
  { code: '331', name: 'Fram Capital Distribuidora' },
  { code: '332', name: 'Acesso Soluções de Pagamento' },
  { code: '335', name: 'Banco Digio' },
  { code: '336', name: 'Banco C6' },
  { code: '340', name: 'Super Pagamentos (Superdigital)' },
  { code: '341', name: 'Itaú Unibanco' },
  { code: '342', name: 'Creditas Sociedade de Crédito Direto' },
  { code: '343', name: 'FFA Sociedade de Crédito' },
  { code: '348', name: 'Banco XP' },
  { code: '349', name: 'AL5 Crédito' },
  { code: '350', name: 'Cooperativa de Crédito Rural de Bela Vista do Paraíso' },
  { code: '352', name: 'Toro Corretora' },
  { code: '354', name: 'Necton Investimentos' },
  { code: '355', name: 'Ótimo Sociedade de Crédito Direto' },
  { code: '359', name: 'Zema Crédito' },
  { code: '360', name: 'Trinus Capital Distribuidora' },
  { code: '362', name: 'Cielo' },
  { code: '363', name: 'Socinal Crédito' },
  { code: '364', name: 'Gerencianet (Efí Bank)' },
  { code: '365', name: 'Sodexo (Simpli)' },
  { code: '366', name: 'Banco Société Générale Brasil' },
  { code: '367', name: 'Vitreo Distribuidora' },
  { code: '368', name: 'Banco CSF (Carrefour)' },
  { code: '370', name: 'Banco Mizuho do Brasil' },
  { code: '371', name: 'Warren Corretora' },
  { code: '373', name: 'UP.P SEP' },
  { code: '374', name: 'Realize Crédito' },
  { code: '376', name: 'Banco J.P. Morgan' },
  { code: '377', name: 'BMS Sociedade de Crédito Direto' },
  { code: '378', name: 'Banco Brasileiro de Crédito' },
  { code: '379', name: 'Cooperforte' },
  { code: '380', name: 'PicPay' },
  { code: '381', name: 'Banco Mercedes-Benz do Brasil' },
  { code: '382', name: 'Fidúcia SCMEPP' },
  { code: '383', name: 'EBANX (Junção Pagamentos)' },
  { code: '384', name: 'Global Finanças SCMEPP' },
  { code: '387', name: 'Banco Toyota do Brasil' },
  { code: '389', name: 'Banco Mercantil do Brasil' },
  { code: '390', name: 'Banco GM' },
  { code: '391', name: 'Cooperativa de Crédito Rural de Ibiam (Sulcredi)' },
  { code: '393', name: 'Banco Volkswagen' },
  { code: '394', name: 'Banco Bradesco Financiamentos' },
  { code: '396', name: 'HUB Pagamentos' },
  { code: '397', name: 'Listo Sociedade de Crédito Direto' },
  { code: '399', name: 'Kirton Bank' },
  { code: '403', name: 'Cora SCD' },
  { code: '404', name: 'SumUp' },
  { code: '407', name: 'Índigo Investimentos' },
  { code: '408', name: 'Bônuscred Sociedade de Crédito Direto' },
  { code: '410', name: 'Planner SCMEPP' },
  { code: '411', name: 'Via Certa Financiadora' },
  { code: '412', name: 'Banco Capital' },
  { code: '414', name: 'Work SCMEPP' },
  { code: '418', name: 'Zipdin Soluções Digitais' },
  { code: '419', name: 'Numbrs Sociedade de Crédito Direto' },
  { code: '421', name: 'Lar Cooperativa de Crédito' },
  { code: '422', name: 'Banco Safra' },
  { code: '423', name: 'Coluna Distribuidora' },
  { code: '425', name: 'Socinal Crédito Direto' },
  { code: '426', name: 'Neon Financeira' },
  { code: '427', name: 'Cooperativa de Crédito Rural de Nova Petrópolis (Cred-Union)' },
  { code: '430', name: 'Cooperativa de Crédito Rural Seibel' },
  { code: '433', name: 'BR-Capital Distribuidora' },
  { code: '435', name: 'Delcredit Sociedade de Crédito Direto' },
  { code: '439', name: 'ID Corretora' },
  { code: '440', name: 'Creditibank' },
  { code: '444', name: 'Trusol Crédito e Financiamento' },
  { code: '447', name: 'UX Instituição de Pagamento' },
  { code: '448', name: 'Hemera Distribuidora' },
  { code: '450', name: 'Fitbank Pagamentos Eletrônicos' },
  { code: '451', name: 'J17 Sociedade de Crédito Direto' },
  { code: '452', name: 'Credifit SCD' },
  { code: '453', name: 'Banco Ribeirão Preto' },
  { code: '454', name: 'Mérito Crédito' },
  { code: '457', name: 'UY3 Sociedade de Crédito Direto' },
  { code: '458', name: 'Hedge Investments' },
  { code: '460', name: 'Unavanti SCD' },
  { code: '461', name: 'ASA Gestão Financeira' },
  { code: '462', name: 'Stark Bank' },
  { code: '463', name: 'Azumi Distribuidora' },
  { code: '464', name: 'Banco Sumitomo Mitsui Brasileiro' },
  { code: '465', name: 'Capital Consig SCD' },
  { code: '467', name: 'Master S/A Crédito' },
  { code: '468', name: 'Portoseg (Crédito Porto)' },
  { code: '469', name: 'PicPay Serviços' },
  { code: '470', name: 'CDC Sociedade de Crédito Direto' },
  { code: '471', name: 'Cooperativa de Economia e Crédito Mútuo dos Servidores Públicos' },
  { code: '473', name: 'Banco Caixa Geral Brasil' },
  { code: '475', name: 'Banco Yale' },
  { code: '477', name: 'Citibank' },
  { code: '478', name: 'GazinCréd' },
  { code: '479', name: 'Banco ItauBank' },
  { code: '481', name: 'Superlógica Sociedade de Crédito Direto' },
  { code: '482', name: 'SBCASH SCD' },
  { code: '484', name: 'Mafex Corretora' },
  { code: '487', name: 'Deutsche Bank' },
  { code: '488', name: 'JPMorgan Chase Bank' },
  { code: '492', name: 'ING Bank' },
  { code: '495', name: 'Banco de La Provincia de Buenos Aires' },
  { code: '505', name: 'Banco Credit Suisse' },
  { code: '506', name: 'RJI Sociedade de Crédito Direto' },
  { code: '507', name: 'SFR Crédito' },
  { code: '509', name: 'Celcoin Instituição de Pagamento' },
  { code: '512', name: 'Finatec Sociedade de Crédito Direto' },
  { code: '513', name: 'ATF SCD' },
  { code: '516', name: 'Qista SCD' },
  { code: '518', name: 'Mercado Crédito SCFI' },
  { code: '519', name: 'Lions Trust Distribuidora' },
  { code: '520', name: 'Pequena Empresa Sociedade de Crédito' },
  { code: '521', name: 'Peac SCD' },
  { code: '522', name: 'Red SCD' },
  { code: '523', name: 'HR Digital SCD' },
  { code: '524', name: 'WNT Capital Distribuidora' },
  { code: '525', name: 'Interfinanceira SCD' },
  { code: '526', name: 'Monitor Crédito' },
  { code: '527', name: 'ATICCA SCD' },
  { code: '528', name: 'Reag Trust Distribuidora' },
  { code: '529', name: 'Pinbank' },
  { code: '530', name: 'Ser Finance SCD' },
  { code: '531', name: 'BMP Money Plus SCD' },
  { code: '532', name: 'Eagle SCD' },
  { code: '534', name: 'FFCresc SCD' },
  { code: '535', name: 'OPEA SCD' },
  { code: '536', name: 'Neon Pagamentos (Banco Votorantim)' },
  { code: '537', name: 'Microcash SCMEPP' },
  { code: '538', name: 'Credial SCD' },
  { code: '540', name: 'Santo Crédito SCD' },
  { code: '541', name: 'FDD SCD' },
  { code: '542', name: 'CloudWalk Instituição de Pagamento' },
  { code: '543', name: '3S Money SCD' },
  { code: '545', name: 'Senso SCD' },
  { code: '546', name: 'U4C Instituição de Pagamento' },
  { code: '547', name: 'BNP Digital SCD' },
  { code: '548', name: 'RPW SCD' },
  { code: '549', name: 'AGInvest SCD' },
  { code: '550', name: 'Mecada Distribuidora' },
  { code: '552', name: 'BHU SCD' },
  { code: '553', name: 'S3 SCD' },
  { code: '554', name: 'Uzzipay Instituição de Pagamento' },
  { code: '555', name: 'Smartpay SCD' },
  { code: '557', name: 'Baribill SCD' },
  { code: '558', name: 'Guavapay' },
  { code: '559', name: 'Kddb Instituição de Pagamento' },
  { code: '560', name: 'Mag Instituição de Pagamento' },
  { code: '561', name: 'Pay Smart' },
  { code: '562', name: 'Iouu SCD' },
  { code: '563', name: 'Alelo' },
  { code: '565', name: 'Orizon Instituição de Pagamento' },
  { code: '566', name: 'Capcons Instituição de Pagamento' },
  { code: '567', name: 'Ifood Pago' },
  { code: '568', name: 'BC Systems Instituição de Pagamento' },
  { code: '569', name: 'Credialanco SCD' },
  { code: '570', name: 'SafraPay' },
  { code: '571', name: 'Credihome SCD' },
  { code: '572', name: 'Omni Banco' },
  { code: '574', name: 'Neon Investimentos' },
  { code: '575', name: 'Jusbrasil SCD' },
  { code: '576', name: 'Baraúna SCD' },
  { code: '577', name: 'Mercantil Financeira' },
  { code: '578', name: 'Conductor Instituição de Pagamento' },
  { code: '579', name: 'Terravista SCD' },
  { code: '580', name: 'RecargaPay' },
  { code: '581', name: 'EcoPayz' },
  { code: '583', name: 'WePag Instituição de Pagamento' },
  { code: '584', name: 'Bank of America Merrill Lynch' },
  { code: '586', name: 'Dibens SCD' },
  { code: '587', name: 'Trust Instituição de Pagamento' },
  { code: '589', name: 'R.O. Bank SCD' },
  { code: '590', name: 'Caixa Prática SCD' },
  { code: '591', name: 'Vision SCD' },
  { code: '592', name: 'Proforte SCD' },
  { code: '593', name: 'Tecnoglass SCD' },
  { code: '595', name: 'Magnetis Investimentos' },
  { code: '596', name: 'N5 Instituição de Pagamento' },
  { code: '597', name: 'Issuing SCD' },
  { code: '598', name: 'LDS SCD' },
  { code: '599', name: 'Planner Trustee Distribuidora' },
  { code: '600', name: 'Banco Luso Brasileiro' },
  { code: '602', name: 'Singulare Corretora' },
  { code: '604', name: 'Banco Industrial do Brasil' },
  { code: '605', name: 'A.J. Renner SCD' },
  { code: '607', name: 'Banco VR' },
  { code: '610', name: 'Banco Paulista' },
  { code: '611', name: 'Banco Paulista S.A.' },
  { code: '612', name: 'Banco Guanabara' },
  { code: '613', name: 'Omni Credito' },
  { code: '623', name: 'Banco PAN' },
  { code: '626', name: 'Banco C6 Consignado' },
  { code: '630', name: 'Banco Smartbank' },
  { code: '633', name: 'Banco Rendimento' },
  { code: '634', name: 'Banco Triângulo' },
  { code: '637', name: 'Banco Sofisa' },
  { code: '641', name: 'Banco Alvorada' },
  { code: '643', name: 'Banco Pine' },
  { code: '652', name: 'Itaú Unibanco Holding' },
  { code: '653', name: 'Banco Voiter (Indusval)' },
  { code: '654', name: 'Banco Digimais' },
  { code: '655', name: 'Banco Votorantim' },
  { code: '707', name: 'Banco Daycoval' },
  { code: '712', name: 'Banco Ourinvest' },
  { code: '735', name: 'Banco Neon' },
  { code: '739', name: 'Banco Cetelem' },
  { code: '741', name: 'Banco Ribeirão Preto' },
  { code: '743', name: 'Banco Semear' },
  { code: '745', name: 'Banco Citibank' },
  { code: '746', name: 'Banco Modal' },
  { code: '747', name: 'Banco Rabobank International Brasil' },
  { code: '748', name: 'Sicredi' },
  { code: '751', name: 'Scotiabank Brasil' },
  { code: '752', name: 'Banco BNP Paribas Brasil' },
  { code: '753', name: 'Novo Banco Continental' },
  { code: '754', name: 'Banco Sistema' },
  { code: '755', name: 'Bank of America Merrill Lynch' },
  { code: '756', name: 'Sicoob' },
  { code: '757', name: 'Banco KEB Hana do Brasil' },
];

/** Formata o código COMPE com 3 dígitos (ex.: "1" -> "001"). */
export function formatBankCode(code: string): string {
  const d = (code ?? '').replace(/\D/g, '');
  return d ? d.padStart(3, '0') : '';
}
