project_id = "ignhvbtqhcyxkwnsqpue"

[functions.suggest-category]
verify_jwt = false

[functions.notify-whatsapp]
verify_jwt = false

[functions.bank-api-proxy]
verify_jwt = false

[functions.credit-consult]
verify_jwt = false

[functions.credit-biometry-analyze]
verify_jwt = false

[functions.cappta-webhook]
verify_jwt = false

[functions.necta-webhook]
verify_jwt = false
